### ISSUE TITLE
form submission with enter does not work

### ISSUE THREAD

**Issue by aokolish** [dbrans/react-number-format-input#1]
I have a form that looks roughly like this:

```
<form onSubmit={this.handleSubmit}>
  <NumberFormatInput {...this.moneyMaskOpts()} onChange={this.onChange} />
  <button>Submit<button />
</form>
```

When I type a value into the input and press enter, I expect it to submit the form, but it does not. I think enter needs to be handled specially to maintain normal browser behavior. Thanks!

**Comment by dbrans** [comment]
Fixed in v0.8.0
