### ISSUE TITLE
option to prevent input of negative numbers

### ISSUE THREAD

**Issue by aokolish** [dbrans/react-number-format-input#3]
It would be great if there was an option that I could pass in to prevent the input of negative numbers. I would like to restrict people from inputting values that are invalid for a field.

**Comment by dbrans** [comment]
Hey Alex,
You can use composition to do this.

``` js
import NumberFormatInput from 'react-number-format-input'
import React from 'react';
export default function MyNumberInput(props) {
  return <NumberFormatInput {...props}, onChange={value => props.onChange(Math.abs(value))/>
}
```

I'd like to try avoiding adding validation and limits to this repo for as long as I can.

**Comment by aokolish** [comment]
cool, that totally works for me :+1:
