### ISSUE TITLE
Some browser key combinations are prevented

### ISSUE THREAD

**Issue by aokolish** [dbrans/react-number-format-input#5]
Example:
1. Open up the demo in Firefox (on a Mac...not sure about Windows)
2. Press Command + T to open a new tab

**Expected:** opens a new tab
**Result:** does nothing

Same thing applies to opening a new window (Command + N).

Command + ~ (to switch between open windows) works on Firefox, but does not work in Safari.

Command + L (to go to the address bar) also does not work in Firefox.

**Comment by joefiorini** [comment]
@aokolish @dbrans Just tested this myself in Firefox and Safari. All the mentioned shortcuts seem to work. Either fixed or no longer an issue?
