### ISSUE TITLE
Question about decimals configuration

### ISSUE THREAD

**Issue by emmenko** [dbrans/react-number-format-input#7]
@dbrans Hey, I just stumbled upon your repo as I was looking for a consistent and flexible implementation regarding formatting input numbers / currencies. I think this topic is not easy at all and the implementation I'm using so far has some really weird and tricky edge cases. So I was hoping to find a much better approach and yours looks promising.

Unfortunately I noticed some weird behaviour about decimals. I noticed that the number of decimals are kind of fixed, whether you defined a min or max number of digits.
This should be fine for e.g. currencies but if you just want to enter an arbitrary number with decimals it kind if imposes you to enter all the decimals.

I've noticed also that when you type numbers, it starts from the smallest decimal number even when I just want to type an integer.

For example (using the demo page), if I want to type `12` I get `0.12`.

Are you aware of this weird behaviour and if so, what's your opinion about it and how should it be fixed?

Thanks in advance!

**Comment by dbrans** [comment]
Hey @emmenko I just saw this! So sorry for the delay. I will fix my github email notifications. 
If you're still interested in discussing:

I based this behavior on other number input behaviors I've seen. Can you provide an example of a number input that behaves more like what you'd expect?

**Comment by dbrans** [comment]
Closing for now. Feel free to ping me if you're still interested in discussing!
